### ISSUE TITLE
fonts.googleapis.com call

### ISSUE THREAD

**Issue by ProductivePhysician** [o10n-x/wordpress-css-optimization#13]
Hi there.
I am seeing a call to 
If I look at my page source, I see that within 
`<script data-o10n `
there are a bunch of calls to stylesheets.
One of those is to 
`[1,"https:\/\/fonts.googleapis.com\/css"]`
How can I remove it please, as I am hosting my fonts locally?
Cheers!

**Comment by optimalisatie** [comment]
The CSS Optimization plugin intends to be purely focused on optimization technologies instead of modifying / controlling WordPress. This enables to control the optimization using JSON that is portable to any website and platform.

The plugin does not automatically exclude Google font CSS. You will need to manually exclude or remove Google font CSS via the URL filter.

![image](https://user-images.githubusercontent.com/8843669/39687321-2c04316c-51ce-11e8-8734-bff0d89d9b40.png)

BTW: did you know that you can time Javascript execution while scripts are concatenated? This allows to execute a heavy marketing related script based on `requestIdleCallback` while other scripts are executed with priority. 

The timed exec feature is of exceptional value for optimization. It enables to achieve perfect Google Lighthouse scores for websites with 3+ mb of heavy marketing related javascript. A 50,000+ product e-commerce website that we recently optimized inserted over 20 marketing related scripts for popups, user review widgets and much more. Some of the marketing widgets included their own jQuery, complete Vue.js library and even TweenMax of 200kb. Using the timed execution functionality this website has a Google Lighthouse 100 performance score while there have been no limitations on functionality (all marketing widgets are still loaded).

Demo: www.verkoop.com

![image](https://user-images.githubusercontent.com/8843669/39687626-992e8c78-51cf-11e8-968d-c389c29d5412.png)

Script execution prioritization (timed exec) is a unique innovation of the optimization plugin.

CSS optimization offers a similar feature for times CSS loading and rendering, including an option to unrender based on a Media Query. This would enable to alter + efficiently load a design based on the mobile device orientation.

**Comment by ProductivePhysician** [comment]
Thanks!
