### ISSUE TITLE
Failed to create directory and Error: mkdir(): File exists rarely comes

### ISSUE THREAD

**Issue by Venomz3** [o10n-x/wordpress-css-optimization#23]
Failed to create cache directory /wp-content/cache/o10n/css/src/06/90/6b/
Failed to create directory /wp-content/cache/o10n/css/src/06/90/6b/ Error: mkdir(): File exists

I reported this even this has happened twice to me and I haven`t been able to reproduce it.  I`ve been trying to find combination how this error comes but I´m not able to find it yet. Using latest version of plugin.

**Comment by optimalisatie** [comment]
Thank you very much for reporting the issue!

When was the last time that the issue occurred? It should have been fixed since `v0.0.77` (3 days ago). Your original issue contains more information.

https://github.com/o10n-x/wordpress-javascript-optimization/issues/12#issuecomment-395890144

**Comment by Venomz3** [comment]
Last time issue occurred was yesterday.  I did give all info that I thought of in that moment.  I did lot of testing and cache empty procedures after update 0.0.77 and I didn`t find any issue. Maybe something has come up with newest update.  I cannot reproduce bug. Now that I´m trying to reproduce seems to be working every case.  If I remember correctly I was randomly clicking to top menu o10n to quickly change settings and empty caches.  I wasn`t specifically hunting bug that`s why I didn`t pay attention what were exact steps.  It sees to come up very rarely.  I`ll get you updated when I have more info.

**Comment by optimalisatie** [comment]
The issue should not be possible since `v0.0.77`. Are you certain that the issue occurred after the update to `0.0.77`?

Normally, `mkdir` should be ultra fast so that there is little chance that another PHP process get's past the directory exists check `file_exists` to create the same directory. 

Since `0.0.77`, when `mkdir` fails, the directory exists check is repeated so that the `File exists` error should not be possible.

```php
// check if directory exists
if (!file_exists($path)) {

    // create directory
    if (!@mkdir($path, $mode, $recursive)) {

        // mkdir failed

        // check if directory has been created by a concurrent process
        if (!file_exists($path)) {

            // directory was not created, report error

            $error = error_get_last();
            throw new \Exception('Failed to create directory ' . $this->safe_path($path) . (($error) ? ' Error: ' . $error['message'] : ' Error: unknown'));
        }
    }

    // set permissions
    @chmod($path, $mode);
} elseif (!is_dir($path) && file_exists($path)) { // verify type

    // path exists as a file
    throw new \Exception('Failed to create directory ' . $this->safe_path($path) . ' Error: path exists as a file (not a directory)');
}
```

**Comment by Venomz3** [comment]
Just less than minute a got this: Javascript Optimization
Error during proxy update (shutdown callback): 
Failed to proxy https://static.xx.fbcdn.net/rsrc.php/v3/y-/r/MC9xhleHEfF.js Error: Failed to create cache directory /wp-content/cache/o10n/js/proxy/87/18/12/
Failed to create directory /wp-content/cache/o10n/js/proxy/87/18/12/ Error: mkdir(): File exists
Failed to proxy https://static.xx.fbcdn.net/rsrc.php/v3/yz/r/DV_9ghLN0WS.js Error: Failed to create cache directory /wp-content/cache/o10n/js/proxy/80/28/d8/
Failed to create directory /wp-content/cache/o10n/js/proxy/80/28/d8/ Error: mkdir(): File exists


Failed to create cache directory /wp-content/cache/o10n/js/proxy/80/28/d8/
Failed to create directory /wp-content/cache/o10n/js/proxy/80/28/d8/ Error: mkdir(): File exists


Failed to create cache directory /wp-content/cache/o10n/js/proxy/87/18/12/
Failed to create directory /wp-content/cache/o10n/js/proxy/87/18/12/ Error: mkdir(): File exists

Failed to create cache directory /wp-content/cache/o10n/css/src/8e/2c/31/
Failed to create directory /wp-content/cache/o10n/css/src/8e/2c/31/ Error: mkdir(): File exists

I don`t know if it`s related  but all I did clicked from top menu to JavaScript optimization.  
Now I got you so info.. maybe..  I moved from wp admin panel to external site and then I came back to wp admin (with pressing back button few times) and clicked JavaScript optimizations from top o10n menu. As soon as I clicked I got those error messages.  And yes I`m certain that issue existed after 0.0.77 update.

**Comment by optimalisatie** [comment]
Could you please confirm that you upgraded all other WPO plugins to the latest version? The `mkdir` functionality is part of the optimization plugin core and to achieve single plugin performance, the plugin core of just one plugin is used. 

We will investigate the issue further.

**Comment by optimalisatie** [comment]
The update from today should prevent the issue. Please let us know if you experience the error again when using the latest versions.

**Comment by Venomz3** [comment]
Using latest version I got this after saving setting Async loading (javascript) and setting config filter:
Failed to create cache directory /wp-content/cache/o10n/css/src/21/5b/67/
Failed to create directory /wp-content/cache/o10n/css/src/21/5b/67/ Error: directory exists after double-check. Please report this issue on Github. (show error info)

error info: {
    "type": 2,
    "message": "mkdir(): File exists",
    "file": "\/wp-content\/plugins\/wordpress-css-optimization\/core\/controllers\/file.class.php",
    "line": 115,
    "_path": "\/wp-content\/cache\/o10n\/css\/src\/21\/5b\/67\/",
    "_date": "Wed, 13 Jun 2018 19:23:41 +0000",
    "_trace": [
        {
            "file": "\/wp-content\/plugins\/wordpress-css-optimization\/core\/controllers\/file.class.php",
            "line": 459,
            "function": "mkdir",
            "class": "O10n\\File",
            "type": "->"
        },
        {
            "file": "\/wp-content\/plugins\/wordpress-css-optimization\/core\/controllers\/cache.class.php",
            "line": 693,
            "function": "directory_path",
            "class": "O10n\\File",
            "type": "->"
        },
        {
            "file": "\/wp-content\/plugins\/wordpress-css-optimization\/controllers\/css.class.php",
            "line": 1702,
            "function": "meta",
            "class": "O10n\\Cache",
            "type": "->"
        },
        {
            "file": "\/wp-content\/plugins\/wordpress-css-optimization\/controllers\/css.class.php",
            "line": 1612,
            "function": "minify_stylesheets",
            "class": "O10n\\Css",
            "type": "->"
        },
        {
            "file": "\/wp-content\/plugins\/wordpress-css-optimization\/controllers\/css.class.php",
            "line": 342,
            "function": "extract",
            "class": "O10n\\Css",
            "type": "->"
        },
        {
            "file": "\/wp-includes\/class-wp-hook.php",
            "line": 286,
            "function": "process_html",
            "class": "O10n\\Css",
            "type": "->"
        },
        {
            "file": "\/wp-includes\/plugin.php",
            "line": 203,
            "function": "apply_filters",
            "class": "WP_Hook",
            "type": "->"
        },
        {
            "file": "\/wp-content\/plugins\/wordpress-css-optimization\/core\/controllers\/output.class.php",
            "line": 82,
            "function": "apply_filters"
        },
        {
            "function": "process_buffer",
            "class": "O10n\\Output",
            "type": "->"
        },
        {
            "file": "\/wp-includes\/functions.php",
            "line": 3730,
            "function": "ob_end_flush"
        },
        {
            "file": "\/wp-includes\/class-wp-hook.php",
            "line": 286,
            "function": "wp_ob_end_flush_all"
        },
        {
            "file": "\/wp-includes\/class-wp-hook.php",
            "line": 310,
            "function": "apply_filters",
            "class": "WP_Hook",
            "type": "->"
        },
        {
            "file": "\/wp-includes\/plugin.php",
            "line": 453,
            "function": "do_action",
            "class": "WP_Hook",
            "type": "->"
        },
        {
            "file": "\/wp-includes\/load.php",
            "line": 679,
            "function": "do_action"
        },
        {
            "function": "shutdown_action_hook"
        }
    ]
}
Here is config filter text that I tryed to save (exclude) : [
  {
    "match": "/https://www.jhhypnoosi.fi/wp-admin/admin-ajax.php?lang.en&action.bookly_render_service&csrf_token.+/",
    "regex": true,
    "async": false,
    "rel_preload": false,
    "exec_timing": {
      "type": "requestAnimationFrame",
      "frame": 1
    },
    "localStorage": {
      "max_size": 10000,
      "update_interval": 3600,
      "expire": 86400,
      "head_update": true
    }
  }
]

**Comment by optimalisatie** [comment]
Thank you for sharing the error report. We suspect that the issue may be related to your server.

The following is happening:

1) PHP checks if the directory exists using `file_exists` (it's the [correct method](http://php.net/manual/en/function.file-exists.php))
The check returns false (directory does not exist)
2) PHP tries to create the directory using `mkdir`
The mkdir method fails with the error `mkdir(): File exists`. This could happen when mkdir is slow so that multiple processes may start the mkdir method for the same directory.
3) PHP explicitly clears the statcache while officially that should not be required for non-existent paths. PHP checks again if the directory exists, this time with 2 methods: `file_exists` and `is_dir`. Again, the function returns false (directory does not exist).

How is this possible?

The file_exists method should be ultra fast. It is almost impossible that a process could become in between and delete the directory just after `mkdir` and just before `file_exists`.

Our first guess is that for some reason (due to an issue with the server environment) the file exists method does not work properly or is slower than the actual file system activity. Perhaps there is a special write cache that will queue disk writes so that file_exists returns false while the write has already been sent (but is still pending) and therefor a second write (`mkdir`) fails on the basis of the queue (and not the actual disk).

```php
if (!file_exists($path)) {

    // create directory
    if (!@mkdir($path, $mode, $recursive)) {

        // mkdir failed
        // check if directory has been created by a concurrent process
        
        // clear stat cache for path (should not be required)
        clearstatcache(true, $path);

        // double check if directory exists
        if (file_exists($path) || is_dir($path)) {
            return true;
        }

        // directory was not created, report error
        $error = error_get_last();

        // directory exists error
        // add stack trace and request to report issue on Github
        // @link https://github.com/o10n-x/wordpress-css-optimization/issues/23
        if ($error && $error['message'] === 'mkdir(): File exists') {
```

We could add another 
```php 
if (!@mkdir($path, $mode, $recursive)) { 
``` 
attempt before processing the `mkdir(): File exists` error, but it doesn't seem something that should logically be needed when the file system functions as intended (in which file_exists and mkdir work with actual file system status).

Do you have an idea why the issue may occur on your server environment?

**Comment by Venomz3** [comment]
I `ll contact my webhotel support and ask about.  I`ll copy text of your last reply to email to have better them better information of issue.  I already suspected server issue or slowness because you wrote that particular function is super fast and should not fail.  I`ll get back when I know more. Yeah it seems illogical to do more checkings… It should be working already.

**Comment by optimalisatie** [comment]
It may be a file system bug. How can `file_exists` return false while `mkdir` returns a `mkdir(): File exists` error?

The latest update contains a tmpfix. It will accept the status of the mkdir file exists error so that the issue will be solved for your server environment, but under the hood there may be a performance issue (`file_exists` does not seem to work as it should).

https://github.com/o10n-x/wordpress-css-optimization/releases/tag/0.0.80
