### ISSUE TITLE
Net_URL2 (rebase): Base-URL must be absolute if reference is not fragment-only 

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-css-optimization#28]
When opening the configuration I get 

Net_URL2 (rebase): Base-URL must be absolute if reference is not fragment-only 

with a red frame... where to fix? what's wrong?

**Comment by AlphaDE** [comment]
The same message is shown in the security plugin.

**Comment by AlphaDE** [comment]
No comment on this?

**Comment by optimalisatie** [comment]
The error originates from Net_URL2. It's a PHP PEAR extension so it's well developed.

https://github.com/pear/Net_URL2
http://pear.php.net/package/Net_URL2/redirected

Do you have an idea what part of the CSS code (URL) may have triggered the error?

In regards to errors, it appears to be misleading but the errors are not 'real time'. PHP Exceptions of all optimization plugins (including errors triggered by visitors of the website) are displayed as soon as you view any of the optimization plugin admin pages.

PHP Exceptions will ensure that you know when something breaks on the website. They are a sort of PHP error log specific to the optimization plugins that provide a notification in the admin that is displayed _once, a few times or for x time_ when using the optimization plugin admin pages.

Another advantage over [WP_Error](https://codex.wordpress.org/Class_Reference/WP_Error) (`wp_die`) is that a website will function without the optimization plugins if anything within (parts of) the optimization plugins fails. The exception is logged using PHP `error_log` and the plugin simply aborts loading and allows WordPress to continue without the plugin.

<details>
 <summary>Show O10n plugin loader PHP code</summary>

```php
### Optimization plugin loader with Exception based abort
try {

    // load the core plugin class
    require O10N_CORE_PATH . 'controllers/core.class.php';
    
    // load core plugin controller
    Core::load();

    // catch plugin errors
} catch (Exception $err) {

    // plugin failed to load
    if (is_admin()) {
        add_action('admin_notices', create_function('', "echo '<div class=\"error\"><h1>".__('Optimization plugin core failed to load', 'o10n') ."</h1><p>".$err->getMessage()."</p></div>';"), (PHP_INT_MAX * -1));
    }

    // write error to log
    error_log('Optimization plugin core failed to load on ' . parse_url($_SERVER['REQUEST_URI'] . ' | Error: '.$err->getMessage(), PHP_URL_PATH));

    return;

    // catch other exceptions (from dependencies, libraries etc.)
} catch (\Exception $err) {

    // add admin notice
    if (is_admin()) {
        add_action('admin_notices', create_function('', "echo '<div class=\"error\"><h1>".__('Optimization plugin core experienced a problem while loading a dependency.', 'o10n') ."</h1><p>".$err->getMessage()."</p></div>';"), (PHP_INT_MAX * -1));
    }
    
    // write error to log
    error_log('Optimization plugin core failed to load a dependency on ' . parse_url($_SERVER['REQUEST_URI'] . ' | Error: '.$err->getMessage(), PHP_URL_PATH));

    return;
}
```
</details>
.

We will improve the error messages in a future update to separate admin usage related errors from PHP Exceptions that occurred on the website (triggered by visitors) and to include a debug backtrace (this is already available when you would enable `O10N_DEV` in `wp-config.php` but that's not recommended for a live website).

### PHP Exceptions

A unique feature of the WPO plugins is that it uses PHP Exceptions that are logged to the WPO plugin admin so that you have a clear view if anything goes wrong. It also enables a website to remain usable if the WPO plugin (or parts of it) fail.

> ### [Why WP_Error Sucks](https://journal.rmccue.io/165/why-wp_error-sucks/)
> As anyone who has worked with WordPress knows, WordPress supported PHP 4 for a long time, even after many other projects had switched. The advantage of this was supporting significantly more hosts, with most PHP 5-only features either not being needed or being easy to reimplement.
> 
> One of the new features added to PHP in PHP 5 was exception handling... 
> 
> https://journal.rmccue.io/165/why-wp_error-sucks/

### PHP errors in browser console

A unique innovation is that PHP errors are also displayed in the browser console when debug mode is enabled. Some of the Exceptions may not be fatal (e.g. a failed regular expression). With debug mode enabled you can find these errors in the browser console for optimization purposes.

![image](https://user-images.githubusercontent.com/8843669/41180460-a03ca1a4-6b6e-11e8-8cbb-599415311831.png)
