### ISSUE TITLE
Ability to select cache folder.

### ISSUE THREAD

**Issue by qiigodev** [o10n-x/wordpress-css-optimization#35]
No folders but our uploads folders are writable in our live environment and this causes WordPress to crash. Adding in the ability to select which folder the plugin writes to would solve this issue.

**Comment by optimalisatie** [comment]
Hi @qiigodev,

Thank you for the feedback!

The option to change the location of the cache directory is already available via the constant `O10N_CACHE_DIR`. You could define it in `wp-config.php`.

```php
# optimization cache directory
define('O10N_CACHE_DIR', '/path/to/cache/');
```

You can also set the permissions for cache files so that it could be easier to manage the files via FTP. It is also possible to set different permissions for files stored in the theme directory, for example when downloading web fonts. By default, files stored in the theme directory use the cache permissions.

```php
# optimization cache permissions
define('O10N_CACHE_CHMOD_FILE', 0664);
define('O10N_CACHE_CHMOD_DIR', 0755);

# optional: custom theme permissions
define('O10N_THEME_CHMOD_FILE', 0664);
define('O10N_THEME_CHMOD_DIR', 0755);
```
