### ISSUE TITLE
Issue with FontAwesome

### ISSUE THREAD

**Issue by RauchenwaldC** [o10n-x/wordpress-css-optimization#39]
When using Minify and Fontawesome is included somehow breaks. Instead of burger menu icon and search it just shows squares -> http://prntscr.com/mo1pd9 (all other font-awesome icons look the same after minifying).

**Comment by optimalisatie** [comment]
Hi RauchenwaldC,

Fontawesome CSS code consists of a basic `@font-face` block and code to define the fonts. 

```css
@font-face{font-family:'FontAwesome';src:url('../fonts/fontawesome-webfont.eot?v=4.7.0'); ... }
```

https://www.w3schools.com/icons/fontawesome_icons_intro.asp

Did you inspect the code to see what may be wrong with the minified code? Are there errors visible in the browser console, for example a 404 not found error for the Fontawesome font file?

What minifier are you using? The default [CssMin.php](https://code.google.com/archive/p/cssmin/), the advanced [YUI Compressor PHP Port](https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port), simple regex or your own custom minifier?

The URL rebaser may enable to resolve a relative path issue. However, if the ultimate performance / data-transfer saving is the goal, you could move the font files to the root directory (e.g. `/f.woff2`) and update the Fontawesome CSS code to link to the root location. It would minimize the font URL to the smallest size possible.

If the fonts are used on every page, an other tip is to load the Fontawesome CSS code using Critical CSS. You could create a dedicated file named `webfonts.css` that is appended to the critical CSS for every page, or a selection of pages using the conditions. When using critical CSS and the correct `font-display` configuration, the fonts will render smoothly and it will be possible to resolve font related Google Lighthouse penalties.

More info by Google: **Controlling Font Performance with font-display**
https://developers.google.com/web/updates/2016/02/font-display

**Comment by RauchenwaldC** [comment]
Thanks for your fast reply. I'm using the CssMin.php but the issue persists with all available methods. 
No 404 in the console. What I could find that may be the reason is https://github.com/madskristensen/WebEssentials2013/issues/326#issuecomment-30859943 as the issue apparently occurs with other minify solutions as well.

**Comment by optimalisatie** [comment]
To resolve the issue, you simply need to look at the small part of the minified CSS code related to FontAwesome and compare it to the original.

I see that you are located in Thailand. FontAwesome uses UTF-8 to write it's icons. If your website uses `windows-874` (Thai) it could explain the issue.  It may be an option to investigate if defining `@charset` resolves the issue.

https://www.w3schools.com/cssref/pr_charset_rule.asp

**Comment by RauchenwaldC** [comment]
Charset is not the issue, as I'm using UTF-8 (my profile hasn't been updated and doesn't reflect my location but just the companies).
Unfortunately, I can't compare the CSS pre and post minification, since I already proceeded to switch to JS+SVG version of FontAwesome.

**Comment by optimalisatie** [comment]
Google does not advise to use SVG fonts. WOFF2 offers better compression and SVG is no longer supported in Chrome.

I am not certain that it's mentioned in the following article, but I read it recently.

**Web Font Optimization**
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization

> Note: There's technically another container format, the SVG font container, but IE and Firefox never supported it, and it is now deprecated in Chrome. As such, it's of limited use and it's intentionally omitted it in this guide.

Best results may be achieved by creating a custom font with just the icons that are needed (minimum size). The following service enables to create a custom FontAwesome font with a selection of icons:

https://icomoon.io/app/

**Comment by RauchenwaldC** [comment]
May be closed. Was caused by some CSS issues.

**Comment by amankapoor** [comment]
I am also facing this problem with all the available minifying options @optimalisatie 

But in my case, I am getting a 404 with font-awesome woff2, woff and ttf files.

The original font-awesome css file as you know uses relative URL.

I have selected the option that converts relative URIs to proper and in the code, the permanent URL that I see is - ```https://staging.site.com/app/cache/o10n/css/0/fonts/fontawesome-webfont.woff2?v=4.7.0``` which doesn't exist.

Even after deselecting the rebasing option and flushing cache, I see the same issue.

So I am getting 404 for the font-awesome files.

How can I fix it?

I am using Trellis to develop and deploy wordpress sites.

**Comment by optimalisatie** [comment]
Hi @amankapoor,

It is very simple in this case: a font is referenced incorrectly which could have many different reasons. 

It is the responsibility of the CSS manager to fix the issue which also leads to the most reliable result.

The automated URL rebaser (PEAR [Net_URL](https://pear.php.net/package/Net_URL)) can provide a solution in many cases, however, it is usually best to manually fix the issue.

### Step 1: why is the font URL incorrect?

Finding a answer to this question likely explains what may went wrong, and how to easily fix it by manually editing the font CSS.

### Step 2: can the font URL be compressed?

While looking at the issue, it may be a good time to consider optimizing the font URL to save more data (this is especially beneficial when font CSS is loaded via Critical CSS). For example, when you use just a few fonts on a website, it may be possible to simply store them in the root directory so that you can reference them in the CSS as `/f.woff2` (8 chars) instead of `https://cdn.domain-name.com/wp-content/themes/MY-THEME-NAME/fonts/font-name.woff2` (81 chars). 

The saving is 73 chars. When using 4 fonts the saving would be `292 bytes`. 

The `above-the-fold` budget is about 14,000 bytes. When finding 3-4 of such savings, you can easily save 1000 bytes which has a significant effect on the ability to achieve (long lasting) perfect performance scores.

More info:

> Due to how TCP estimates the capacity of a connection (i.e. TCP Slow Start), a new TCP connection cannot immediately use the full available bandwidth between the client and the server. Because of this, the server can send up to 10 TCP packets on a new connection (~14KB) in first roundtrip, and then it must wait for client to acknowledge this data before it can grow its congestion window and proceed to deliver more data.

https://developers.google.com/speed/docs/insights/mobile
